###

Post http://localhost:3000/user

Content-Type: application/json
{
    "name": "John",
    "_id": "122"
}


###
GET  http://localhost:3000/user

###
GET http://localhost:3000/user/1234589

###
PUT http://localhost:3000/user/

Content-Type: application/json
{
    "name": "John",
    "_id": "122"
}

###
DELETE http://localhost:3000/user/122

# Check post

###
GET http://localhost:3000/post
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY1OWE4MzlkMGI4ZjRmZDcxY2IwOGUzNiIsImlhdCI6MTcwNDYyNjU5MiwiZXhwIjoxNzA0NjMwMTkyfQ.OWK4ZhIMCGMesvTtELK9IfPCgAKX76LpMGcobUfkD4E



###
GET http://localhost:3000/post/1234589

###
POST http://localhost:3000/post

Content-Type: application/json
{
    "title": "Your Title",
    "message": "Your Message",
    "owner": "Owner's Name"
}
   

###
PUT http://localhost:3000/post/1

###
DELETE http://localhost:3000/post/1
###

################## CHECK AUTH#####################


###
POST http://localhost:3000/auth/register

Content-Type: application/json
{
    
    "email": "shlomi",
    "password": "123456"
}



###
POST http://localhost:3000/auth/login

Content-Type: application/json
{
    
    "email": "shlomi",
    "password": "123456"
}

###
POST http://localhost:3000/auth/logout


















